# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: email
        # in_memory:
        #     memory:
        #       users:
        #             ryan:
        #                 password: '$2y$12$0zHs4ekx8bXpBCQajmxAfu1WJ3YoZXn/98NUcoAvtlQfH6Y39yJMq'
        #                 roles: 'ROLE_USER'
        #             admin:
        #                 password: '$2y$12$tYAtd7lE/x4/QUFwBSvx9eqHRiENj/vqz0GrSbOsq0raJ1Fjqjig6'
        #                 roles: 'ROLE_ADMIN'
    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: app_security_index
                check_path: app_security_index
            logout:
                path: logout
                target: app_default_index
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~
    access_control:
      # require ROLE_ADMIN for /admin*
      - { path: ^/connexion$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/administration, roles: ROLE_ADMIN }
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
